version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: newsflow-data-postgres
    environment:
      POSTGRES_DB: newsflow
      POSTGRES_USER: newsflow
      POSTGRES_PASSWORD: newsflow1234
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - newsflow-network

  airflow:
    image: apache/airflow:2.9.1
    container_name: newsflow-airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://newsflow:newsflow1234@postgres:5432/newsflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__WEBSERVER__SECRET_KEY: newsflow-airflow-secret
    ports:
      - "8082:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - airflow_plugins:/opt/airflow/plugins
    depends_on:
      - postgres
    networks:
      - newsflow-network
    command: >
      bash -c "airflow db migrate &&
               airflow users create --username admin --password admin
               --firstname NewsFlow --lastname Admin
               --role Admin --email admin@newsflow.com &&
               airflow webserver & airflow scheduler"

volumes:
  postgres_data:
  airflow_plugins:

networks:
  newsflow-network:
    driver: bridge